let express = require('express');
let path = require('path');
let fs = require('fs');
let cookieParser = require('cookie-parser');
let logger = require('morgan');
let sassMiddleware = require('node-sass-middleware');
const expressOasGenerator = require('express-oas-generator');

require("./persistence/config").init();

let indexRouter = require('./routes/index.route');
let usersRouter = require('./routes/users.route');
let authRouter = require('./routes/auth.route');

let app = express();

//Setup to generate a swagger config file
//Serves as a starter for a more extended description
//of the API (autogenerated)
expressOasGenerator.init(app,
    function (spec) {
        return spec;
    },
    'efgm-api.swagger.json',
    60 * 1000);

// view engine init
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

//Setup logger
// create a write stream (in append mode)
let accessLogStream = fs.createWriteStream(path.join(__dirname, 'access.log'), {flags: 'a'});
app.use(logger('combined', {stream: accessLogStream}));
app.use(logger('dev'));

app.use(express.json());
app.use(express.urlencoded({extended: false}));
app.use(cookieParser());
app.use(sassMiddleware({
    src: path.join(__dirname, 'public'),
    dest: path.join(__dirname, 'public'),
    indentedSyntax: true, // true = .sass and false = .scss
    sourceMap: true
}));
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/api', usersRouter);
app.use('/auth', authRouter);

// error handler
app.use(function (err, req, res, next) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};

    // render the error page
    res.status(err.status || 500);
    res.render('error');
});

module.exports = app;
